# Stage 1 - the build process
FROM node:8.11.3 as prod-build
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json yarn.lock /usr/src/app/
RUN yarn
COPY . /usr/src/app
RUN yarn build

# Stage 2 - the production environment
FROM nginx:1.13.9-alpine

RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx

RUN rm -rf /usr/share/nginx/html/*
COPY --from=prod-build /usr/src/app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
