version: '3.5'
services:
  prod-build:
    build:
      context: .
      dockerfile: Dockerfile-prod
    container_name: prod-build
    restart: always
    env_file:
      - .env
    ports:
      - 8089:80
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=production