version: '3.5'
services:
  public-build:
    container_name: public-build
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_PUBLIC=true
        - REACT_APP_DOMAIN=http://192.168.0.68
        - REACT_APP_PATH=unioilQA/public/index.php/api/cms
        - REACT_APP_IMG_PATH=unioilQA
    restart: always
    ports:
      - 8090:80
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'